"""create todos2 table and add status column

Revision ID: 0eda1ca99d7c
Revises: 51cb227410f4
Create Date: 2025-05-29 15:28:36.747759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0eda1ca99d7c'
down_revision: Union[str, None] = '51cb227410f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos2', sa.Column('status', sa.String(), nullable=True))
    op.drop_column('todos2', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos2', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('todos2', 'status')
    # ### end Alembic commands ###
