"""create todos table

Revision ID: 51cb227410f4
Revises: de4200c6e6c7
Create Date: 2025-05-29 15:26:48.006751

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51cb227410f4'
down_revision: Union[str, None] = 'de4200c6e6c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todos2',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_todos2_id'), 'todos2', ['id'], unique=False)
    op.create_index(op.f('ix_todos2_title'), 'todos2', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_todos2_title'), table_name='todos2')
    op.drop_index(op.f('ix_todos2_id'), table_name='todos2')
    op.drop_table('todos2')
    # ### end Alembic commands ###
