"""increase password length

Revision ID: e6f28501dab3
Revises: 70fe1e60636e
Create Date: 2025-06-05 13:25:20.597866

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6f28501dab3'
down_revision: Union[str, None] = '70fe1e60636e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_todos2_id'), table_name='todos2')
    op.drop_index(op.f('ix_todos2_title'), table_name='todos2')
    op.drop_table('todos2')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todos2',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('completed', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('todos2_pkey'))
    )
    op.create_index(op.f('ix_todos2_title'), 'todos2', ['title'], unique=False)
    op.create_index(op.f('ix_todos2_id'), 'todos2', ['id'], unique=False)
    # ### end Alembic commands ###
