import { EXPO_PUBLIC_SUPABASE_URL, EXPO_PUBLIC_SUPABASE_ANON_KEY, EXPO_PUBLIC_DEEPSEEK_API_KEY } from '@env'

export const CONFIG = {
  SUPABASE_URL: EXPO_PUBLIC_SUPABASE_URL || '',
  SUPABASE_ANON_KEY: EXPO_PUBLIC_SUPABASE_ANON_KEY || '',
  DEEPSEEK_API_KEY: EXPO_PUBLIC_DEEPSEEK_API_KEY || '',
}; 