export const data = [
    {
        mobileImage: require('../assets/1st.jpeg'),
        mobileId: 1,
        mobileName: 'Product 1',
        mobilePrice: 19.99,
        mobileDescription: 'Galaxy S25 Ultras rounded design expresses a unified identity for the Galaxy S series. With its sleek and strong titanium frame and a built-in S Pen, its an ultra-modern, vision of bold design.5',
    },
    {
        mobileImage: require('../assets/2nd.jpeg'),
        mobileId: 2,
        mobileName: 'Product 2',
        mobilePrice: 17.99,
        mobileDescription: 'The Samsung Galaxy A72 is a premium smartphone with a powerful 8GB RAM, 128GB storage, and a 6.7-inch display. It features a 60Hz refresh rate and a 19:9 aspect ratio, making it a perfect choice for those looking for an eye-catching display and a powerful processor.',
    },
    {
        mobileImage: require('../assets/3rd.png'),
        mobileId: 3,
        mobileName: 'Product 3',
        mobilePrice: 24.99,
        mobileDescription: 'The Samsung Galaxy S21 Ultra is a premium smartphone with a powerful 12GB RAM, 256GB storage, and a 6.7-inch display. It features a 60Hz refresh rate and a 19:9 aspect ratio, making it a perfect choice for those looking for an eye-catching display and a powerful processor.',
    },
    {
        mobileImage: require('../assets/4th.jpeg'),
        mobileId: 4,
        mobileName: 'Product 4',
        mobilePrice: 22.99,
        mobileDescription: 'The Samsung Galaxy S21 Ultra is a premium smartphone with a powerful 12GB RAM, 256GB storage, and a 6.7-inch display. It features a 60Hz refresh rate and a 19:9 aspect ratio, making it a perfect choice for those looking for an eye-catching display and a powerful processor.',
    },
    {
        mobileImage: require('../assets/5th.jpeg'),
        mobileId: 5,
        mobileName: 'Product 5',
        mobilePrice: 19.99,
        mobileDescription: 'The Samsung Galaxy S21 Ultra is a premium smartphone with a powerful 12GB RAM, 256GB storage, and a 6.7-inch display. It features a 60Hz refresh rate and a 19:9 aspect ratio, making it a perfect choice for those looking for an eye-catching display and a powerful processor.',
    },
    {
        mobileImage: require('../assets/6th.avif'),
        mobileId: 6,
        mobileName: 'Product 6',
        mobilePrice: 17.99,
        mobileDescription: 'The Samsung Galaxy S21 Ultra is a premium smartphone with a powerful 12GB RAM, 256GB storage, and a 6.7-inch display. It features a 60Hz refresh rate and a 19:9 aspect ratio, making it a perfect choice for those looking for an eye-catching display and a powerful processor',
    },
    {
        mobileImage: require('../assets/7th.avif'),
        mobileId: 7,
        mobileName: 'Product 7',
        mobilePrice: 24.99,
        mobileDescription: 'The Samsung Galaxy S21 Ultra is a premium smartphone with a powerful 12GB RAM, 256GB storage, and a 6.7-inch display. It features a 60Hz refresh rate and a 19:9 aspect ratio, making it a perfect choice for those looking for an eye-catching display and a powerful processor.',
    },
    {
        mobileImage: require('../assets/8th.avif'),
        mobileId: 8,
        mobileName: 'Product 8',
        mobilePrice: 22.99,
        mobileDescription: 'The Samsung Galaxy S21 Ultra is a premium smartphone with a powerful 12GB RAM, 256GB storage, and a 6.7-inch display. It features a 60Hz refresh rate and a 19:9 aspect ratio, making it a perfect choice for those looking for an eye-catching display and a powerful processor.',
    },
    {
        mobileImage: require('../assets/9th.avif'),
        mobileId: 9,
        mobileName: 'Product 9',
        mobilePrice: 19.99,
        mobileDescription: 'The Samsung Galaxy S21 Ultra is a premium smartphone with a powerful 12GB RAM, 256GB storage, and a 6.7-inch display. It features a 60Hz refresh rate and a 19:9 aspect ratio, making it a perfect choice for those looking for an eye-catching display and a powerful processor.',
    },
    {
        mobileImage: require('../assets/10th.avif'),
        mobileId: 10,
        mobileName: 'Product 10',
        mobilePrice: 17.99,
        mobileDescription: 'The Samsung Galaxy S21 Ultra is a premium smartphone with a powerful 12GB RAM, 256GB storage, and a 6.7-inch display. It features a 60Hz refresh rate and a 19:9 aspect ratio, making it a perfect choice for those looking for an eye-catching display and a powerful processor.',
    },
    {
        mobileImage: require('../assets/11th.jpeg'),
        mobileId: 11,
        mobileName: 'Product 11',
        mobilePrice: 24.99,
        mobileDescription: 'The Samsung Galaxy S21 Ultra is a premium smartphone with a powerful 12GB RAM, 256GB storage, and a 6.7-inch display. It features a 60Hz refresh rate and a 19:9 aspect ratio, making it a perfect choice for those looking for an eye-catching display and a powerful processor.',
    },
    {
        mobileImage: require('../assets/12th.jpeg'),
        mobileId: 12,
        mobileName: 'Product 12',
        mobilePrice: 22.99,
        mobileDescription: 'The Samsung Galaxy S21 Ultra is a premium smartphone with a powerful 12GB RAM, 256GB storage, and a 6.7-inch display. It features a 60Hz refresh rate and a 19:9 aspect ratio, making it a perfect choice for those looking for an eye-catching display and a powerful processor.',
    },
    {
        mobileImage: require('../assets/13th.jpeg'),
        mobileId: 13,
        mobileName: 'Product 13',
        mobilePrice: 19.99,
        mobileDescription: 'The Samsung Galaxy S21 Ultra is a premium smartphone with a powerful 12GB RAM, 256GB storage, and a 6.7-inch display. It features a 60Hz refresh rate and a 19:9 aspect ratio, making it a perfect choice for those looking for an eye-catching display and a powerful processor.',
    }
]




// export const data = [
//     {
//       mobileImage: require('../assets/iphone5.jpg'),
//       mobileId: 1,
//       mobileName: 'iPhone 5',
//       mobileColor: 'Black, White',
//       mobileRAM: '1 GB',
//       mobileStorage: '16 GB, 32 GB, 64 GB',
//       mobilePrice: 199.99,
//       mobileDescription: 'The iPhone 5 features a 4-inch Retina display, A6 chip, and a stunning design with a larger screen than its predecessors.',
//     },
//     {
//       mobileImage: require('../assets/iphone6.jpg'),
//       mobileId: 2,
//       mobileName: 'iPhone 6',
//       mobileColor: 'Gold, Silver, Space Gray',
//       mobileRAM: '1 GB',
//       mobileStorage: '16 GB, 64 GB, 128 GB',
//       mobilePrice: 299.99,
//       mobileDescription: 'The iPhone 6 comes with a 4.7-inch display, A8 chip, and improved camera performance. A sleek design and better battery life.',
//     },
//     {
//       mobileImage: require('../assets/iphone7.jpg'),
//       mobileId: 3,
//       mobileName: 'iPhone 7',
//       mobileColor: 'Black, Jet Black, Gold, Rose Gold, Silver',
//       mobileRAM: '2 GB',
//       mobileStorage: '32 GB, 128 GB, 256 GB',
//       mobilePrice: 399.99,
//       mobileDescription: 'The iPhone 7 introduces the A10 Fusion chip, better camera, and water resistance, marking a leap forward in mobile technology.',
//     },
//     {
//       mobileImage: require('../assets/iphone8.jpg'),
//       mobileId: 4,
//       mobileName: 'iPhone 8',
//       mobileColor: 'Space Gray, Silver, Gold',
//       mobileRAM: '2 GB',
//       mobileStorage: '64 GB, 256 GB',
//       mobilePrice: 499.99,
//       mobileDescription: 'iPhone 8 features a glass design with wireless charging, a faster A11 Bionic chip, and improved camera capabilities.',
//     },
//     {
//       mobileImage: require('../assets/iphoneX.jpg'),
//       mobileId: 5,
//       mobileName: 'iPhone X',
//       mobileColor: 'Space Gray, Silver',
//       mobileRAM: '3 GB',
//       mobileStorage: '64 GB, 256 GB',
//       mobilePrice: 999.99,
//       mobileDescription: 'The iPhone X introduces an OLED display, Face ID, and a stunning new design with no home button. Powered by A11 Bionic chip.',
//     },
//     {
//       mobileImage: require('../assets/iphoneXR.jpg'),
//       mobileId: 6,
//       mobileName: 'iPhone XR',
//       mobileColor: 'Black, Blue, Coral, Yellow, White, Red',
//       mobileRAM: '3 GB',
//       mobileStorage: '64 GB, 128 GB, 256 GB',
//       mobilePrice: 749.99,
//       mobileDescription: 'The iPhone XR offers a 6.1-inch LCD display, A12 Bionic chip, and impressive color choices. Offers a perfect balance of power and style.',
//     },
//     {
//       mobileImage: require('../assets/iphoneXS.jpg'),
//       mobileId: 7,
//       mobileName: 'iPhone XS',
//       mobileColor: 'Space Gray, Silver, Gold',
//       mobileRAM: '4 GB',
//       mobileStorage: '64 GB, 256 GB, 512 GB',
//       mobilePrice: 999.99,
//       mobileDescription: 'The iPhone XS is powered by the A12 Bionic chip with a Super Retina OLED display and dual-camera system for amazing photos.',
//     },
//     {
//       mobileImage: require('../assets/iphone11.jpg'),
//       mobileId: 8,
//       mobileName: 'iPhone 11',
//       mobileColor: 'Black, Green, Yellow, Purple, Red, White',
//       mobileRAM: '4 GB',
//       mobileStorage: '64 GB, 128 GB, 256 GB',
//       mobilePrice: 699.99,
//       mobileDescription: 'The iPhone 11 features a dual-camera system, Night Mode, and the new A13 Bionic chip, delivering powerful performance and great photos.',
//     },
//     {
//       mobileImage: require('../assets/iphone12.jpg'),
//       mobileId: 9,
//       mobileName: 'iPhone 12',
//       mobileColor: 'Black, Blue, Green, Red, White',
//       mobileRAM: '4 GB',
//       mobileStorage: '64 GB, 128 GB, 256 GB',
//       mobilePrice: 799.99,
//       mobileDescription: 'iPhone 12 brings 5G connectivity, an OLED Super Retina display, and Ceramic Shield for durability.',
//     },
//     {
//       mobileImage: require('../assets/iphone13.jpg'),
//       mobileId: 10,
//       mobileName: 'iPhone 13',
//       mobileColor: 'Pink, Blue, Midnight, Starlight, Red, Green',
//       mobileRAM: '4 GB',
//       mobileStorage: '128 GB, 256 GB, 512 GB',
//       mobilePrice: 899.99,
//       mobileDescription: 'The iPhone 13 offers improved battery life, A15 Bionic chip, and better camera performance, including Cinematic Mode.',
//     },
//     {
//       mobileImage: require('../assets/iphone14.jpg'),
//       mobileId: 11,
//       mobileName: 'iPhone 14',
//       mobileColor: 'Blue, Purple, Midnight, Starlight, Red, Yellow',
//       mobileRAM: '6 GB',
//       mobileStorage: '128 GB, 256 GB, 512 GB',
//       mobilePrice: 999.99,
//       mobileDescription: 'iPhone 14 introduces emergency SOS via satellite, A15 Bionic chip, and an improved 48 MP primary camera.',
//     },
//     {
//       mobileImage: require('../assets/iphone15.jpg'),
//       mobileId: 12,
//       mobileName: 'iPhone 15',
//       mobileColor: 'Black, White, Green, Blue, Yellow, Red',
//       mobileRAM: '6 GB',
//       mobileStorage: '128 GB, 256 GB, 512 GB',
//       mobilePrice: 1099.99,
//       mobileDescription: 'The iPhone 15 comes with dynamic island, 48MP main camera, and an upgraded A16 chip for enhanced performance.',
//     },
//     {
//       mobileImage: require('../assets/iphone16.jpg'),
//       mobileId: 13,
//       mobileName: 'iPhone 16',
//       mobileColor: 'Titanium, Black, Silver, Blue',
//       mobileRAM: '8 GB',
//       mobileStorage: '256 GB, 512 GB, 1 TB',
//       mobilePrice: 1199.99,
//       mobileDescription: 'The iPhone 16 features the new A17 chip, 5G enhanced, a new design with titanium materials, and advanced camera system.',
//     }
//   ];
  